CREATE OR REPLACE DATABASE NVIDIA_NIMS_RAG_STREAMLIT;

CREATE OR REPLACE STAGE MODEL_STAGE_RAG ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE COMPUTE POOL IF NOT EXISTS NVIDIA_NIMS_RAG_STREAMLIT_S
MIN_NODES = 1
MAX_NODES = 1
INSTANCE_FAMILY = GPU_NV_S;

DESCRIBE COMPUTE POOL NVIDIA_NIMS_RAG_STREAMLIT_S;

CREATE OR REPLACE STAGE SPECS 
    DIRECTORY = ( ENABLE = TRUE ) 
    ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );

CREATE OR REPLACE IMAGE REPOSITORY NVIDIA_NIMS_RAG_STREAMLIT_REPO;

SHOW IMAGE REPOSITORIES;