SHOW IMAGES IN IMAGE REPOSITORY NVIDIA_NIMS_RAG_STREAMLIT_REPO;

DROP SERVICE IF EXISTS NIMS_RAG_MISTRAL_STREAMLIT_RAG;

DESCRIBE COMPUTE POOL NVIDIA_NIMS_RAG_STREAMLIT_S;
ALTER COMPUTE POOL NVIDIA_NIMS_RAG_STREAMLIT_S RESUME;

CREATE SERVICE NIMS_RAG_MISTRAL_STREAMLIT_RAG
    IN COMPUTE POOL NVIDIA_NIMS_RAG_STREAMLIT_S
    FROM @SPECS
    SPECIFICATION_FILE='NIMS_RAG_mistral_streamlit_rag.YAML'
    EXTERNAL_ACCESS_INTEGRATIONS = (ALLOW_ALL_EAI);

SELECT SYSTEM$GET_SERVICE_STATUS('NIMS_RAG_MISTRAL_STREAMLIT_RAG');

CALL SYSTEM$GET_SERVICE_LOGS('NIMS_RAG_MISTRAL_STREAMLIT_RAG', '0', 'streamlit-handler');

SHOW ENDPOINTS IN SERVICE NIMS_RAG_MISTRAL_STREAMLIT_RAG;